import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import { ThemeProviders } from "@/components/Providers/ThemeProvider";
import CommandPalette from "@/components/CommandPalette";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProviders>
        <body
          className={`${inter.className} bg-theme-light dark:bg-theme-dark`}
        >
          <CommandPalette>
            <Header />
            {children}
          </CommandPalette>
        </body>
      </ThemeProviders>
    </html>
  );
}
